services:
  - type: web
    name: modres-backend
    env: docker
    plan: free
    buildCommand: docker build -t modres-backend .
    startCommand: gunicorn -w 2 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
      - key: CLOUD_MODE
        value: true
